// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDkAGfud3uPFJdG5o6FRnkGuJmj7KvfCRk',
    appId: '1:78758121359:web:a37129aaada187051fc5fa',
    messagingSenderId: '78758121359',
    projectId: 'moneytor-e0622',
    authDomain: 'moneytor-e0622.firebaseapp.com',
    storageBucket: 'moneytor-e0622.firebasestorage.app',
    measurementId: 'G-8JG9Q3VFTL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDFoRAAuscMn8ewMgDNOhZFLZ_7paK0dvE',
    appId: '1:78758121359:android:2de8a3f7ad7c31d71fc5fa',
    messagingSenderId: '78758121359',
    projectId: 'moneytor-e0622',
    storageBucket: 'moneytor-e0622.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD9cZADsnENOewMqSwTeRf52i7BBYCzQmo',
    appId: '1:78758121359:ios:9a54a09ef0667eae1fc5fa',
    messagingSenderId: '78758121359',
    projectId: 'moneytor-e0622',
    storageBucket: 'moneytor-e0622.firebasestorage.app',
    iosClientId: '78758121359-1ffu972pugh765dqipqe0vg1nqi4o6dp.apps.googleusercontent.com',
    iosBundleId: 'com.example.moneytor',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD9cZADsnENOewMqSwTeRf52i7BBYCzQmo',
    appId: '1:78758121359:ios:9a54a09ef0667eae1fc5fa',
    messagingSenderId: '78758121359',
    projectId: 'moneytor-e0622',
    storageBucket: 'moneytor-e0622.firebasestorage.app',
    iosClientId: '78758121359-1ffu972pugh765dqipqe0vg1nqi4o6dp.apps.googleusercontent.com',
    iosBundleId: 'com.example.moneytor',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDkAGfud3uPFJdG5o6FRnkGuJmj7KvfCRk',
    appId: '1:78758121359:web:cddee3aa26a721861fc5fa',
    messagingSenderId: '78758121359',
    projectId: 'moneytor-e0622',
    authDomain: 'moneytor-e0622.firebaseapp.com',
    storageBucket: 'moneytor-e0622.firebasestorage.app',
    measurementId: 'G-FJZCWFLL0Z',
  );
}
